#!/bin/bash
cat >/etc/nginx/nginx.conf <<EOF
user www-data;
worker_processes 4;
pid /run/nginx.pid;
daemon off;

events {
  worker_connections 768;
  # multi_accept on;
}

http {
  # we limit both on IP (single machine) as well as project ID
  limit_req_zone  \$binary_remote_addr  zone=one:10m   rate=3r/s;
  limit_req_zone  \$projectid  zone=two:10m   rate=3r/s;

  # limit_req_status requires nginx 1.3.15 or newer
  limit_req_status 429;

  server {
    listen   80;
    server_name $SERVER_NAME;

    proxy_set_header   Host                 \$http_host;
    proxy_set_header   X-Real-IP            \$remote_addr;
    proxy_set_header   X-Forwarded-For      \$proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto    \$scheme;
    proxy_redirect     off;

    # keepalive + raven.js is a disaster
    keepalive_timeout 0;

    # use very aggressive timeouts
    proxy_read_timeout 5s;
    proxy_send_timeout 5s;
    send_timeout 5s;
    resolver_timeout 5s;
    client_body_timeout 5s;

    # buffer larger messages
    client_max_body_size 150k;
    client_body_buffer_size 150k;

    location / {
      proxy_pass        http://$SENTRY_PORT_9000_TCP_ADDR:9000;
    }

    location ~* /api/(?P<projectid>\d+/)?store/ {
      proxy_pass        http://$SENTRY_PORT_9000_TCP_ADDR:9000;

      limit_req   zone=one  burst=3  nodelay;
      limit_req   zone=two  burst=10  nodelay;
    }

  }
}


#mail {
# # See sample authentication script at:
# # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
# # auth_http localhost/auth.php;
# # pop3_capabilities "TOP" "USER";
# # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
# server {
#   listen     localhost:110;
#   protocol   pop3;
#   proxy      on;
# }
#
# server {
#   listen     localhost:143;
#   protocol   imap;
#   proxy      on;
# }
#}

EOF
nginx
